### ISSUE TITLE
Prepare and show data

### ISSUE THREAD

**Issue by bensle** [bensle/capstone-project#1]
## Value proposition

**As a** user,
**I want to** see proposals of activities on screen
**so that** i can find something new to do in my spare time.

## Description

<img src=https://user-images.githubusercontent.com/104505674/175504115-a192c09e-6167-423b-b673-130866180495.png width=320px>

<img src=https://user-images.githubusercontent.com/104505674/175504256-c2147642-abdf-469a-8907-9702aad21c3b.png width=320px>

## Acceptance criteria

- [x] Activities  should scroll y
- [x] Activities should not scroll x
- [x] ActivityCard-component should show name of activity first
- [x] ActivityCard-component should also show location, tags and a link for further informations

## Complexity

Medium 

## Tasks

- [x] prepare sample data
- [x] Create branch
- [x] Add base styles
- [x] Setup Storybook for ActivityCard-component
- [x] Implement ActivityCard-component
- [x] Add `state` for Activities
- [x] Write specs for ActivityCard-component
- [x] Add ActivityCard-component to app

**Comment by ahohnsen** [comment]
Hi Benjamin,

great work. I have a few suggestions:

**Comment by ahohnsen** [comment]
Hi Benjamin,

**Comment by ahohnsen** [comment]
Hi Benjamin,

nicely done. I have a few suggestions:

Description:
You should display real data (e.g. activity names, tags and information) instead of placeholders/description of what will be displayed. Meaning: the scribble should show a realistic version of what you are going to build.

Acceptance criteria:
The first two points are redundant as this is already visible in the scribble. However, to mention if the page is scrollable is a very good point 👍🏼 

Task:
I would suggest to find another name for your component instead of "result" as it is not very descriptive. Maybe you can name your component "Activity", "ActivityCard" or something similiar.

**Comment by bensle** [comment]
Updated your suggestions

**Comment by ahohnsen** [comment]
Great job 👍🏼 
As discussed earlier, please specify the following point of your acceptance criteria:

_-  Usually More infos will be a link_

**Comment by mbosselmann** [comment]
Hi Benjamin,
I like your user story! 👍 Almost nothing to complain,I only have one remark that is related to Andrea's last comment on your user story about the criterion 'Usually "More infos" will be a link. If not available "More Infos" would be textcontent':
- Based on your scribbles, it is not clear to me what is meant by "more info". Only the link or also the other data that is displayed in the card? I think you should better relate this to your scribble, so that it is more understandable what is meant by "more info".

Happy hacking! :)

**Comment by bensle** [comment]
>     * Based on your scribbles, it is not clear to me what is meant by "more info". Only the link or also the other data that is displayed in the card? I think you should better relate this to your scribble, so that it is more understandable what is meant by "more info".
> 
 Thanks for having a look at it! I updated my acceptance criteria so that the card will have " location, tags and a link for further information"
 This might change in a later state because i want to let the user add new interesting activities. But for now, at this point only links will be presented.
