### ISSUE TITLE
Add LocalStorage

### ISSUE THREAD

**Issue by bensle** [bensle/capstone-project#10]
## Value proposition

**As a** user,
**I want to** save my Favorites & added activities in LocalStorage
**so that** i can see my Favorites & added activities after refreshing the browser or if the browser was closed

## Acceptance criteria

- [x] after setting an activity as favorites, favorites will be saved in localstorage
- [x] added activities will be saved in localstorage

## Complexity

small/medium

## Tasks

- [x] create a branch
- [x] add localstorage
- [x] save favorites and (added) activities in localstorage
