### ISSUE TITLE
Delete favorites

### ISSUE THREAD

**Issue by bensle** [bensle/capstone-project#11]
## Value proposition

**As a** user,
**I want to** have the option to delete favorites
**so that** i can remove activities from my favorites-list in case i don't like them anymore and don't want to save them any longer.

## Description
<img src=https://user-images.githubusercontent.com/104505674/177041514-c8788e5b-4e15-480c-9a72-b425b9018c28.png
 width=320px>

## Acceptance criteria

- [ ] click on "FavoriteIcon" deletes favorite from list
- [ ] Favorites list will be updated immediately

## Complexity

small

## Tasks

- [ ] Create branch
- [ ] Updating Activity card component
- [ ] Write function for delete activity from favorites
- [ ] Write specs for deleting Favorites 
- [ ] Add Favorites-Page to App

**Comment by stefankorder** [comment]
Good work, but there are words doubled in your first sentence.
