### ISSUE TITLE
Add Navigation & routing

### ISSUE THREAD

**Issue by bensle** [bensle/capstone-project#12]
## Value proposition

**As a** user,
**I want to** have a navigation bar
**so that** I can navigate through the app more conveniently.
## Description
<img src=https://user-images.githubusercontent.com/104505674/178849288-cfcb805a-b971-4092-9e44-52c840838eef.png width=320px>

![Screenshot 2022-07-14 at 00 41 48]()

## Acceptance criteria

- [x] Navigation will be a sidebar
- [x] Navigation can be toggled
- [x] All Pages are accessible via Navigation
- [x] Navigation will close after page was chosen
- [x] AddActivities will be converted to a page and no longer be a modal
- [x] All Navigationbuttons on the pages will be removed
- [x] Routing should be added and show the correct path

## Complexity

medium

## Tasks

- [x] Create branch
- [x] Create Pages: Favorites, Activities, AddActivities, Map
- [x] Remove all unnecessary Buttons 
- [x] Create story for navigation component
- [x] add routing
- [x] Add navigation component to App
