### ISSUE TITLE
Add a map and show database on map

### ISSUE THREAD

**Issue by bensle** [bensle/capstone-project#16]
## Value proposition

**As a** user,
**I want to** have a map 
**so that** i can see where the different activities are located.

## Description
<img src=https://user-images.githubusercontent.com/104505674/178225285-5b93de27-6f96-49eb-aaf9-81663df56d67.png
 width=320px>

## Acceptance criteria

- [x] map should display the activities from database with marker on the map
- [x] marker should display onclick tooltip with name and location of the activity
- [x] Map will be accessible through basic navigation

## Complexity

medium

## Tasks

- [x] create a branch
- [x] import database to map
- [x] import location and name to the map
- [x] add basic navigation to map
- [x] add map to app

**Comment by ahohnsen** [comment]
Hey Ben,

good start. I have some questions/thoughts:

- I am wondering what the "1", "2" and "3" in the bottom of the scribble mean? Should this be a navigation? I assume these are buttons. Will they later on show really the text "1", "2" and "3" or something else? Please remember to fill your scribble with real content.
- Will the map be displayed on the main page of your app? Will the activity list you have already implemented still be accessible? If so, how can the user switch between the list and the map? All this information should be included in your scribble and acceptance criteria.
- It would be also nice if you display an example marker/tooltip of your map. You write that the marker displays an "onclick" tooltip. Does that mean that first only a marker is visible and when the user clicks it, a tooltip with name and location will pop up or what happens on click? Will the user go to a detailed view of the activity?

**Comment by bensle** [comment]
Updated scribble and AC.
