### ISSUE TITLE
Display new added Activites on map

### ISSUE THREAD

**Issue by bensle** [bensle/capstone-project#17]
## Value proposition

**As a** user,
**I want to** to see the new added activities on map as well
**so that** i can see where they are located

## Description
<img src=https://user-images.githubusercontent.com/104505674/178226845-5206a3c8-4269-4914-9f65-35bbf8995fbb.png
 width=320px>

## Acceptance criteria

- [x] activities added by the user should also be displayed on the map
- [x] Input "Location" is a livesearch for location
- [x] locationresult will be displayed and can be chosen onclick
- [x] onclick sets die inputvalue of locationinput to clicked searchresult
- [x] activities should display onclick tooltip with name and location on the map
- [x] Activities will be added through navigation "Add"

## Complexity

medium

## Tasks

- [x] Create branch
- [x] update story and spec for AddActivityForm
- [x] Inputfield "location" musst handle input in a way to get longitude & latitude from that location
- [x] add geolocation search to AddActivitiesForm
- [x] geolocation musst provide name, latitude and longitude for setting new activities
- [x] add updated form to app

**Comment by ahohnsen** [comment]
Hey Ben,

great feature! :) 

Please see my comments on your previous user story. Same principles apply here. 

As well you wrote:  _Inputfield "location" musst handle input in a way to get longitude & latitude from that location_
I would add in the acceptance criteria how the user will input the location, meaning will the user be able to enter any location or does a dropdown menu appear with suggestions for existing locations... or does the user even need to type in the coordinates?

And one more question: What do you mean by "ModalInput"? It sounds a bit confusing as your input field is not a modal, I assume 🤔 maybe it's best to rename that.

**Comment by bensle** [comment]
Updated scribble and AC
