### ISSUE TITLE
Add a flyTo Location to Activitiycards

### ISSUE THREAD

**Issue by bensle** [bensle/capstone-project#19]
## Value proposition

**As a** user,
**I want to** click on the location of my choosen activity
**so that** i can find them easily on map and dont have to search for them

## Description
<img src=https://user-images.githubusercontent.com/104505674/179982330-19b231cd-adb5-44ee-afe5-377ff1e5b0c2.png
 width=320px>

## Acceptance criteria

- [ ] Within the activitycards the user should be able to click the location
- [ ] click on location should transfer the user to map component
- [ ] map component should display chosen location centered and zoomed in

## Complexity

medium

## Tasks

- [ ] Create branch
- [ ] add logic for transferring the user from activites(/home) directly to chosen Activity on map
- [ ] add spec for "transferring" function
- [ ] update spec for activity card
