### ISSUE TITLE
Activity-Filter by duration

### ISSUE THREAD

**Issue by bensle** [bensle/capstone-project#2]
## Value proposition

**As a** user,
**I want to** filter the activities based on duration
**so that** i can find activities that fit my available time

## Description

<img src=https://user-images.githubusercontent.com/104505674/175531638-474a3e5f-9531-4045-bd5b-9c09ee1a8d58.png width=320px>

## Acceptance criteria

- [x] Activity-Filter are added as buttons
- [x] No filter is selected at page load
- [x] Activities should update after a filter was selected / button was clicked
- [x] After click, Activities should show the filtered activities
- [x] Activities should scroll 
- [x] Activity-Filter should not scroll and always be seen and available on top

## Complexity

medium

## Tasks

- [x] Create branch
- [x] Setup Storybook for Activity-Filter/Button component
- [x] Write logic for filtering
- [x] Implement Activity-Filter component
- [x] write specs for Activity-Filter component
- [x] Add Activity-Filter component to App

**Comment by ahohnsen** [comment]
Hey Ben,

I am wondering which options will there be available when I click on the filter button. It would be nice to have a scribble to see that. If the user can filter by duration, maybe it would be also cool to show the estimated duration in the information of each activity. 🤔 

Please double-check also your acceptance criteria. Some of the points are already visible in the scribble and therefore do not need to be listed there.

Additionally, I would suggest to rephrase your value proposition e.g.:

_As a user,
I want to filter the activities based on duration
so that I can find results that fit my available time_

**Comment by mbosselmann** [comment]
Hi Benjamin,
good job! 👍 I like this user story too, but I have two remarks:
- like Andrea I also think it would be a good idea to add a time frame to each duration category for the user to know what means "short break" in minutes or hours
- and is there also the possibility to remove the filter to get back to the initial state of the list (maybe by clicking the filter again)? 🤔 You should specify this in your acceptance criteria

**Comment by bensle** [comment]
I've updated the whole story and changed the filteroption. I named the filter in a different way. Now the user can see how much spare time he should have.

**Comment by mbosselmann** [comment]
Hi Benjamin,
I think this is a good idea! 👍  I approve. ✅
