### ISSUE TITLE
Add Input error Message and remaining characters

### ISSUE THREAD

**Issue by bensle** [bensle/capstone-project#2]
## Value proposition
**As a** user ,
**I want to** see a specific ErrorMessage if the add Topic failed,
**so that**I can handle that failed attemp. 

## Description

<img src=https://user-images.githubusercontent.com/104505674/174678035-5e397895-1207-4f9b-9cb3-3c5dbe578292.png width=320px>

## Acceptance criteria
- [ ] Input should display the remaining characters
- [ ] an error message should be displayed if input is blank

## Complexity
Small 

## Tasks
- [ ] Create branch
- [ ] Setup Storie for TopicInput
- [ ] Write specs for TopicInput
