### ISSUE TITLE
Add Styling - Activities

### ISSUE THREAD

**Issue by bensle** [bensle/capstone-project#21]
## Value proposition

**As a** user,
**I want to** have a well styled app
**so that** i can enjoy using the app

## Description
<img src=''
 width=320px>

## Acceptance criteria

- [x] styling should be consistent all over the map
- [x] same elements/components should look the same all over the app (Buttons, Cards shown on different pages, bodyfont, icons)
- [x] font(s) should be easy to read
- [x] font size should not be specified in "px"

## Complexity

small to medium

## Tasks

- [x] create a branch
- [x] add styling
- [x] check for a11y

**Comment by ahohnsen** [comment]
Hey Ben,


>  styling should be consitent all over the map


There is a small typo: _"styling should be consi**s**tent all over the map"_
As well, I think here you could be a bit more specific 🤔 as another developer I would not know what to do here.
