### ISSUE TITLE
Delete Activities

### ISSUE THREAD

**Issue by bensle** [bensle/capstone-project#24]
## Value proposition

**As a** user,
**I want to** delete activities
**so that** activities that I don't like are no longer displayed to me

## Description
<img src=https://user-images.githubusercontent.com/104505674/178233661-8d244ae4-47b2-43bd-a542-32c114ce76b2.png
 width=320px>

## Acceptance criteria

- [x] delete button should be added to all activity cards
- [x] delete button will also be at favotites cards
- [x] a infobox will explain the icons at favorites page
- [x] clicking delete should permanently delete the activity
- [x] Click on deleteButton opens a modal for user confirmation
- [x] after confirmation activity will be deleted

## Complexity

small to medium

## Tasks

- [x] Create branch
- [x] add delete function
- [x] add spec for delete function

**Comment by ahohnsen** [comment]
Hey Ben,

Great job! I just have one question: Will the activity be deleted directly or is any confirmation before deleting required from the user? Will the user get any notification that the activity was deleted successfully?

If you wanna implement anything of the above, it would be good to show that in your scribbles as well as mentioning it in the acceptance criteria.
