### ISSUE TITLE
Add deletebutton to Topic

### ISSUE THREAD

**Issue by bensle** [bensle/capstone-project#3]
## Value proposition
**As a** user,
**I want to** delete topics,
**so that** i can keep my topics organized by removing topics that are done.

## Description

<img src=https://user-images.githubusercontent.com/104505674/174679249-f33291dc-e54e-4ee9-9400-0c5a904fbebe.png width=320px>

## Acceptance criteria
- [ ] A delete button should be added to all topics
- [ ] A dialog should open to confirm the delete
- [ ] The topic should be deleted if confirmed
- [ ] Order of remaining Topics should not be altered

## Complexity
Medium 

## Tasks
- [ ] Create branch
- [ ] Setup Storie for deletebutton
- [ ] add modal asking for confirmation
