### ISSUE TITLE
Activity-Filter by type

### ISSUE THREAD

**Issue by bensle** [bensle/capstone-project#3]
## Value proposition

**As a** user,
**I want to** filter the activities also by type
**so that** i can filter the activities not only by duration but also by there type in order to find activities that fit my time and my preferred type.

## Description

<img src=https://user-images.githubusercontent.com/104505674/175536551-c4379705-14b3-4531-af69-fe3518575e50.png width=320px>

## Acceptance criteria

- [x] Type of activity filter will be a button
- [x] No Typefilter is preselected
- [x] Only one Type filter can be selected
- [x] Activities should update after a filter was selected / clicked
- [x] Activities should show the filtered activities
- [x] Activities should scroll 
- [x] Activity-Type-Filter should not scroll and always be seen and available on top
- [x] Both filter (type & duration) can be applied at the same time

## Complexity

Small 

## Tasks

- [x] Create branch
- [x] Update Storybook for Filter component
- [x] Implement Type-Filter component (variant)
- [x] Write specs for Type-Filter component
- [x] Add Type-Filter component to App

**Comment by ahohnsen** [comment]
Hey Benjamin, 

As your second and third user story are very similar, please have a look at my suggestions for your second story :) 
Additionally, I think you can have a look at your tasks here again: As you already created the filter component in your previous story, you can simply update that component for this story instead of setting up storybook etc. again.
