### ISSUE TITLE
Styling for /Home

### ISSUE THREAD

**Issue by bensle** [bensle/capstone-project#37]
## Value proposition

**As a** user,
**I want to** have a well styled app
**so that** i can enjoy using the app

## Description
<img src=''
 width=320px>
![roam1](https://user-images.githubusercontent.com/104505674/180239145-7e741ff6-abb0-49d0-9c27-7c74b068747f.jpg)

## Acceptance criteria

- [x] styling should be consistent all over the map
- [x] same elements/components should look the same all over the app (Buttons, Cards shown on different pages, bodyfont, icons)
- [x] font(s) should be easy to read
- [x] font size should not be specified in "px"
- [x] update readme.md of my repository and show sample screenshots

## Complexity

small to medium

## Tasks

- [x] create a branch
- [x] add styling
