### ISSUE TITLE
Reset Filter Button

### ISSUE THREAD

**Issue by bensle** [bensle/capstone-project#4]
## Value proposition

**As a** user,
**I want to** reset the chosen filter on a single click
**so that** i can set a new filter or go back to all activities on a single click

## Description

<img src=https://user-images.githubusercontent.com/104505674/175285802-74c423f7-3c94-411d-a97c-fa67ce5c66db.png width=320px>

## Acceptance criteria

- [ ] Each filter should have a button to reset the filter
- [ ] Each filter can be reseted individually
- [ ] After resetting a filter the new activities should be displayed
- [ ] The filter menu should also display "no filter"

## Complexity

Small 

## Tasks

- [ ] Create branch
- [ ] Update Storybook Filter-component
- [ ] Write specs for delete-filter button
- [ ] Add delete-filter button to app
