### ISSUE TITLE
User Input for adding new activities

### ISSUE THREAD

**Issue by bensle** [bensle/capstone-project#7]
## Value proposition

**As a** user,
**I want to** add new interesting activities to the list
**so that** they are stored for later usage, i can share them with others, find them again and have all my activities in one list.

## Description
<img src=https://user-images.githubusercontent.com/104505674/176899074-fb256eff-6a81-450f-abee-b2af9bf6c044.png width=320px>

## Acceptance criteria

- [x] Form should open onclick (Button on Activites"Page"
- [x] Form should be an overlay
- [x] Overlay should close on closing/cancel button or by clicking the backdrop
- [x] All input data should be submitted on "Add"
- [x] New activity should be added to existing activities 
- [x] New activity should be rendered with existing activities
- [x] Overlay should close if new activity was submitted by clicking "add"
- [x] "Name" and "Location" should only allow text
- [x] "Type" and "Duration" will be a drop-down to choose from
- [x] "More infos" is not required. If user sets more Infos it should be a checked if its a valid url.
- [x] All input field should show an Error message if input is not correct

## Complexity

medium to large

## Tasks

- [x] Create branch
- [x] Create story for AddActivity component
- [x] Adding inputs, buttons and selectors to form
- [x] Collecting data drom all inputs
- [x] Pushing new entry to existing 
- [x] Write specs for AddActivity component component
- [x] Add AddActivity component to App
