### ISSUE TITLE
Set favorites

### ISSUE THREAD

**Issue by bensle** [bensle/capstone-project#9]
## Value proposition

**As a** user,
**I want to** add my most popular activities to my favorites
**so that** don't have to search for them if want to do/visit them later (again).

## Description
<img src=https://user-images.githubusercontent.com/104505674/176933587-c34ddbed-5436-4f64-a78b-ca1c1f3e096c.png
 width=320px>
<img src=https://user-images.githubusercontent.com/104505674/177041514-c8788e5b-4e15-480c-9a72-b425b9018c28.png
 width=320px>

## Acceptance criteria

- [x] click on "FavoriteIcon" sets activity as favorite
- [x] setting a favorite opens Favorites-page
- [x] Back-button on Favorites-Page brings the user back to activities
- [x] click on "FavoriteIcon" on FavoritesPage deletes favorite from list
- [x] Favorites list will be updated immediately
- [x] ActivitiesPage will have a button to get access to FavoritesPage

## Complexity

medium

## Tasks

- [x] Create branch
- [x] Updating Activity card component
- [x] Write function for setting activity as favorite
- [x] Create Favorites Page
- [x] Create Back-button
- [x] Write specs for Button (back) & Favorite (add/set)
- [x] Write function for delete activity from favorites
- [x] Write specs for deleting Favorites 
- [x] Add Favorites-Page to App

**Comment by stefankorder** [comment]
Good work, but there are words doubled in your first sentence.
